[[backend_pools]]

matcher = "Host('httpbin.localhost')"
addresses = ["127.0.0.1:8081", "127.0.0.1:8082", "127.0.0.1:8083"]
schemes = ["HTTP"]
strategy = { RoundRobin = {} }

# Compress all data
[backend_pools.middlewares.Compression]