[[backend_pools]]

matcher = "Host('httpbin.localhost')"
addresses = ["127.0.0.1:8081", "127.0.0.1:8082", "127.0.0.1:8083"]
schemes = ["HTTP"]
strategy = { RoundRobin = {} }

# Enable HTTP Basic auth via LDAP
[backend_pools.middlewares.Authentication]
ldap_address = "ldap://172.28.1.7:1389"
user_directory = "ou=users,dc=example,dc=org"
rdn_identifier = "cn"
recursive = false