[[backend_pools]]

matcher = "Host('whoami.localhost')"
addresses = ["127.0.0.1:8084", "127.0.0.1:8085", "127.0.0.1:8086"]
schemes = ["HTTP"]
strategy = { RoundRobin = {} }

# Limit the amount of requests a client can do
[backend_pools.middlewares.RateLimiter]
limit = 5
window_sec = 10