# http_address = "[::]:80"
# https_address = "[::]:443"

# ------------------------------------------------------------------------------
# Pool 1
# ------------------------------------------------------------------------------
[[backend_pools]]
# this matches *.whoami.localhost and whoami.localhost
matcher = "HostRegexp('(.*\\.)?whoami\\.localhost$')"
addresses = ["[::1]:8084", "127.0.0.1:8085", "[2001:3200:3200::1:6]:80"]
schemes = ["HTTP"]
strategy = { StickyCookie = { cookie_name = "lb_cookie", http_only = false, secure = false, same_site = { Lax = {} }, inner = { RoundRobin = {} } } }

[backend_pools.health_config]
path = "/"
slow_threshold = 150
timeout = 400

[backend_pools.middlewares.CustomErrorPages]
location = "examples/errorpages/"
errors = [404, 429, 500]

[backend_pools.middlewares.RateLimiter]
limit = 5
window_sec = 10

[backend_pools.middlewares.Compression]

# ------------------------------------------------------------------------------
# Pool 2
# ------------------------------------------------------------------------------
[[backend_pools]]
matcher = "Host('httpbin.localhost')"
addresses = ["172.28.1.1:80", "172.28.1.2:80", "172.28.1.3:80"]
schemes = ["HTTP"]
strategy = { Random = {} }

[backend_pools.middlewares.Compression]

[backend_pools.middlewares.MaxBodySize]
limit = 256

# ------------------------------------------------------------------------------
# Pool 3
# ------------------------------------------------------------------------------
[[backend_pools]]
matcher = "Host('https.localhost')"
addresses = ["172.28.1.1:80", "172.28.1.2:80", "172.28.1.3:80"]
schemes = ["HTTP", "HTTPS"]
strategy = { IPHash = {} }

[backend_pools.middlewares.HttpsRedirector]

[backend_pools.middlewares.Authentication]
ldap_address = "ldap://172.28.1.7:1389"
user_directory = "ou=users,dc=example,dc=org"
rdn_identifier = "cn"
recursive = false

[backend_pools.middlewares.Compression]

# ------------------------------------------------------------------------------
[certificates]
"https.localhost" = { Local = { certificate_path = "examples/x509/https.localhost.cer", private_key_path = "examples/x509/https.localhost.key" } }

[health_interval]
check_every = 8
