[[backend_pools]]

matcher = "Host('https.localhost')"
addresses = ["127.0.0.1:8081", "127.0.0.1:8082", "127.0.0.1:8083"]
schemes = ["HTTPS"]
strategy = { RoundRobin = {} }

[[backend_pools]]

matcher = "Host('whoami.localhost')"
addresses = ["127.0.0.1:8084", "127.0.0.1:8085", "127.0.0.1:8086"]
schemes = ["HTTPS"]
strategy = { RoundRobin = {} }

[certificates]
"https.localhost" = { Local = { certificate_path = "examples/x509/https.localhost.cer", private_key_path = "examples/x509/https.localhost.key" } }

# Won't work with a local domain. Replace with your domain and email.
# "whoami.localhost" = { ACME = { email = "yourmail@example.de", staging = false, persist_dir = "./certificates" } }
